DROP TABLE IF EXISTS GRAPH_DATA;

CREATE TABLE GRAPH_DATA (
    D DATE,
    TEAM VARCHAR(250) NOT NULL,
    CODE VARCHAR(250) NOT NULL,
    V DECIMAL(10,2) NOT NULL
) 
AS SELECT * FROM CSVREAD('classpath:/data.csv');

DROP TABLE IF EXISTS TBL_USERS;

CREATE TABLE TBL_USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);
